// Export utilities for generating PDFs and copying data to clipboard

export async function copyToClipboard(data: Record<string, any>[]): Promise<boolean> {
  if (data.length === 0) {
    alert('No data to copy')
    return false
  }

  const headers = Object.keys(data[0])
  const rows = [
    headers.join('\t'), // Use tabs for easy Excel paste
    ...data.map(row => 
      headers.map(header => {
        const value = row[header]
        if (value instanceof Date) {
          return value.toLocaleDateString()
        }
        if (value === null || value === undefined) {
          return ''
        }
        return String(value)
      }).join('\t')
    )
  ]
  
  const content = rows.join('\n')

  try {
    await navigator.clipboard.writeText(content)
    return true
  } catch (err) {
    console.error('Failed to copy:', err)
    alert('Failed to copy to clipboard')
    return false
  }
}

export function exportToPrintablePage(title: string, content: string) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    alert('Please allow popups to export')
    return
  }

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title} - Medical Advocacy Assistant</title>
      <style>
        * { box-sizing: border-box; }
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          max-width: 800px; 
          margin: 0 auto; 
          padding: 40px 20px;
          color: #1f2937;
          line-height: 1.6;
        }
        h1 { 
          color: #db2777; 
          border-bottom: 2px solid #fbcfe8;
          padding-bottom: 10px;
          margin-bottom: 30px;
        }
        h2 { 
          color: #be185d; 
          margin-top: 30px;
          margin-bottom: 15px;
        }
        h3 {
          color: #4b5563;
          margin-top: 20px;
        }
        .item { 
          background: #fdf2f8; 
          border: 1px solid #fbcfe8;
          border-radius: 8px; 
          padding: 15px; 
          margin: 15px 0;
        }
        .item-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
        }
        .item-title {
          font-weight: 600;
          font-size: 1.1em;
        }
        .badge {
          background: #fce7f3;
          color: #be185d;
          padding: 4px 12px;
          border-radius: 20px;
          font-size: 0.85em;
        }
        .meta { 
          color: #6b7280; 
          font-size: 0.9em;
          margin-top: 8px;
        }
        .section {
          margin-bottom: 30px;
        }
        .footer { 
          margin-top: 50px; 
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          color: #9ca3af; 
          font-size: 0.85em;
          text-align: center;
        }
        .question-item {
          padding: 10px 0;
          border-bottom: 1px solid #fce7f3;
        }
        .question-item:last-child {
          border-bottom: none;
        }
        .priority-high { color: #dc2626; }
        .priority-medium { color: #d97706; }
        .priority-low { color: #059669; }
        @media print {
          body { padding: 20px; }
          .item { break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <h1>📋 ${title}</h1>
      ${content}
      <div class="footer">
        <p>Generated by Medical Advocacy Assistant on ${new Date().toLocaleDateString()}</p>
        <p>This document is for personal use and sharing with healthcare providers.</p>
      </div>
    </body>
    </html>
  `

  printWindow.document.write(html)
  printWindow.document.close()
  
  // Auto-trigger print dialog
  setTimeout(() => {
    printWindow.print()
  }, 250)
}

// Format helpers
export function formatDate(date: Date): string {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}
